// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TorServices.Data;

#nullable disable

namespace TorServices.Migrations
{
    [DbContext(typeof(TorrentDbContext))]
    [Migration("20260506085342_AddBitfieldPersistence")]
    partial class AddBitfieldPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TorServices.Models.TorrentProgress", b =>
                {
                    b.Property<string>("TorrentId")
                        .HasColumnType("text");

                    b.Property<byte[]>("Bitfield")
                        .HasColumnType("bytea");

                    b.Property<int>("CompletedPieces")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPieces")
                        .HasColumnType("integer");

                    b.HasKey("TorrentId");

                    b.ToTable("TorrentProgresses");
                });

            modelBuilder.Entity("TorServices.Models.TorrentRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MagnetUri")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputDir")
                        .HasColumnType("text");

                    b.Property<string>("TorrentPath")
                        .HasColumnType("text");

                    b.Property<string>("UserClientId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserClientId");

                    b.ToTable("Torrents");
                });

            modelBuilder.Entity("TorServices.Models.UserClient", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId");

                    b.ToTable("UserClients");
                });

            modelBuilder.Entity("TorServices.Models.TorrentProgress", b =>
                {
                    b.HasOne("TorServices.Models.TorrentRecord", "Torrent")
                        .WithOne("ProgressInfo")
                        .HasForeignKey("TorServices.Models.TorrentProgress", "TorrentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torrent");
                });

            modelBuilder.Entity("TorServices.Models.TorrentRecord", b =>
                {
                    b.HasOne("TorServices.Models.UserClient", "User")
                        .WithMany("Downloads")
                        .HasForeignKey("UserClientId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TorServices.Models.TorrentRecord", b =>
                {
                    b.Navigation("ProgressInfo");
                });

            modelBuilder.Entity("TorServices.Models.UserClient", b =>
                {
                    b.Navigation("Downloads");
                });
#pragma warning restore 612, 618
        }
    }
}
